# Generated by Django 5.1.3 on 2024-12-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
